<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
  </PropertyGroup>

  <ItemGroup>
    <None Include="CRTOnly.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="morelinq" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ATAS.Indicators">
      <HintPath>..\libs\ATAS.Indicators.dll</HintPath>
    </Reference>
    <Reference Include="ATAS.Indicators.Technical">
      <HintPath>..\libs\ATAS.Indicators.Technical.dll</HintPath>
    </Reference>
    <Reference Include="OFT.Attributes">
      <HintPath>..\libs\OFT.Attributes.dll</HintPath>
    </Reference>
    <Reference Include="OFT.Localization">
      <HintPath>libs\OFT.Localization.dll</HintPath>
    </Reference>
    <Reference Include="OFT.Rendering">
      <HintPath>..\libs\OFT.Rendering.dll</HintPath>
    </Reference>
    <Reference Include="OFT.Rendering.Wpf">
      <HintPath>..\libs\OFT.Rendering.Wpf.dll</HintPath>
    </Reference>
    <Reference Include="Utils.Common">
      <HintPath>..\libs\Utils.Common.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="copy $(OutDir)\$(AssemblyName).dll $(UserProfile)\AppData\Roaming\ATAS\Indicators" />
	</Target>


</Project>
